#!/bin/bash

SELF="$0"
SRC=mjsonu.h
DEST=mjsonu.out
MAINDEF="TEST_mjsonu__"

. cpp_proj_defines

LINK="$MMCD_LINK"
COMPILER="$MMCD_COMPILER"
INCDIR=$MMCD_INCDIR # " -I.. " 

#x=$devinstalldir
# just move it local for now 
#SRC=$MMCD_SRCDIR/$SRC
SRC=./$SRC

WARNS=$MMCD_WARNS

DEBUG="$MMCD_DEBUG" # " -gdwarf-3 -O0 "
OPT="$MMCD_OPT" # " -O3 "
PROFILE="$MMCD_PROFILE" # " -O3 -gdwarf-3 -pg "
FLAGS="$DEBUG"

RUN_DATA="mjsonu.txt"
compile()
{
mmcd_h_compile
}
run()
{
"./$DEST" -source "$RUN_DATA" -quit  
}

help()
{
echo Usage $0 
cat "$0" | grep "=="  | grep -v grep | sed -e 's/.*==//' | sed -e 's/"[^"]*$//' 
}
while [ "$*" != "" ]
do
start="$*"
if [ "$1" == "-help" ]
then
help
shift
fi

if [ "$1" == "-compile" ]
then
compile
shift
fi
if [ "$1" == "-opt" ]
then
FLAGS=$OPT
shift
fi

if [ "$1" == "-run" ]
then
shift
#run  $*
run 
#shift
fi

if [ "$1" == "-install" ]
then
x=$devinstalldir
if [ "$x" != "" ]
then
echo cp "$DEST" "$x/$DEST"
echo cp "$x/$DEST" "$x/$DEST."`date +%Y-%m-%d-%s`
cp "$x/$DEST" "$x/$DEST."`date +%Y-%m-%d-%s`
cp "$DEST" "$x/$DEST"
else
echo no install dir $devinstalldir
fi
shift
fi


if [ "$*" == "$start" ]
then
help
exit -1
fi
done

